In [16]:
import pandas as pd
import numpy as np

ai_p= pd.read_csv(r"data_noshuffle\ai_opt.csv")
#ai_p = ai_p.reset_index()
#Rand_p=pd.read_csv(r"data_noshuffle\Rand_p.csv")
##Rand_p = Rand_p.reset_index()
intm1_p=pd.read_csv(r"data_noshuffle\intm1_opt.csv")
##intm1_p = intm1_p.reset_index()
intm2_p=pd.read_csv(r"data_noshuffle\intm2_opt.csv")
##intm2_p = intm2_p.reset_index()
vaso1_p=pd.read_csv(r"data_noshuffle\vaso1_opt.csv")
##vaso5_p = vaso5_p.reset_index()
vaso2_p=pd.read_csv(r"data_noshuffle\vaso2_opt.csv")
##vaso10_p = vaso10_p.reset_index()
vaso3_p=pd.read_csv(r"data_noshuffle\vaso3_opt.csv")
#3vaso15_p = vaso15_p.reset_index()

ai_p_new=pd.read_csv(r"data_noshuffle\ai_opt_new.csv")
#ai_p_new = ai_p_new.reset_index()
intm1_p_new=pd.read_csv(r"data_noshuffle\intm1_opt_new.csv")
#intm1_p_new = intm1_p_new.reset_index()
intm2_p_new=pd.read_csv(r"data_noshuffle\intm2_opt_new.csv")
#intm2_p_new = intm2_p_new.reset_index()
vaso1_p_new=pd.read_csv(r"data_noshuffle\vaso1_opt_new.csv")
#vaso5_p_new = vaso5_p_new.reset_index()
vaso2_p_new=pd.read_csv(r"data_noshuffle\vaso2_opt_new.csv")
#vaso10_p_new = vaso10_p_new.reset_index()
vaso3_p_new=pd.read_csv(r"data_noshuffle\vaso3_opt_new.csv")
#vaso15_p_new = vaso15_p_new.reset_index()
#ai_p.head()

In [1]:
import pandas as pd
import numpy as np


intm3_p=pd.read_csv(r"data_noshuffle\intm3_opt.csv")
##intm1_p = intm1_p.reset_index()
intm3_p_new=pd.read_csv(r"data_noshuffle\intm3_opt_new.csv")

In [2]:
data = pd.read_csv("data\data.csv")
train_ids = pd.read_csv(r"D:\Liling\OneDrive - University of Pittsburgh\master_thesis\q_learning_discrete_state\data\train_id.csv")
#train_ids = train_ids[:2000]
train_df = data[data.hosp_id.isin(train_ids.hosp_id.tolist())]
test_ids = pd.read_csv(r"D:\Liling\OneDrive - University of Pittsburgh\master_thesis\q_learning_discrete_state\data\test_id.csv")
test_df = data[data.hosp_id.isin(test_ids.hosp_id.tolist())]

In [10]:
ai_p

,state,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,action
0,1,0.904,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,1
1,2,0.004,0.004,0.004,0.004,0.004,0.904,0.004,0.004,0.004,...,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,6
2,3,0.904,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,1
3,4,0.904,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,1
4,5,0.004,0.004,0.004,0.004,0.004,0.904,0.004,0.004,0.004,...,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,746,0.904,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,1
746,747,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,0.004,0.004,0.004,0.004,0.904,0.004,0.004,0.004,0.004,21
747,748,0.904,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,1
748,749,0.904,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,1
749,750,0.904,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,1

In [118]:
train_df[train_df.reward_vaso5==-5]

,Unnamed: 0,hosp_id,interval,sofa_total,norepi_equiv,lactate,action,dead_90,reward_orig,state,next_state,new_state,new_next_state,last_record,vaso_change,reward_intm1,reward_intm2,reward_vaso5,reward_vaso10,reward_vaso15
679,679,+7Krm6q8zu2sjdl0xAe+nOM3QcR858banND6lTsu9Io=,16.0,10.0,0.20,1.2,4.0,0.0,0,546,546,343,496,0,1.20,0.557625,0.532625,-5,-10,-15
955,955,+BmKTNyKHadHVmUMDrND/qWFnpalsM0KFsl/PUEYgIQ=,7.0,16.0,1.20,15.0,25.0,1.0,0,233,233,618,296,0,1.20,1.926486,1.901486,-5,-10,-15
971,971,+BuAcGbzMc/mfSILbVuwDmB/JZ4D9sV3zqTFyX/fKw8=,11.0,12.0,2.20,8.9,15.0,1.0,0,226,501,486,486,0,1.80,2.053055,2.178055,-5,-10,-15
972,972,+BuAcGbzMc/mfSILbVuwDmB/JZ4D9sV3zqTFyX/fKw8=,12.0,11.0,4.40,6.9,20.0,1.0,0,501,157,486,304,0,2.20,1.593337,1.343337,-5,-10,-15
974,974,+BuAcGbzMc/mfSILbVuwDmB/JZ4D9sV3zqTFyX/fKw8=,14.0,9.0,0.00,5.3,1.0,1.0,0,157,169,270,263,1,4.40,0.000000,0.000000,-5,-10,-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307867,307867,zYoftZ1NHljB/LtLUcQwqGlsUvigs9IsvdSMxXDYF0M=,18.0,11.0,1.20,2.9,25.0,0.0,0,476,91,283,318,1,1.20,0.000000,0.000000,-5,-10,-15
307919,307919,za9vDIkrZKOcO2N/slG/JJf7UHnX4wKboGA0lQRs5q0=,7.0,11.0,1.20,11.2,10.0,1.0,0,309,217,283,422,0,1.20,0.833736,0.458736,-5,-10,-15
308556,308556,zguqA+7IERik9KejbrtfEdyxS5mkYBUfagDysFXKyys=,8.0,16.0,2.20,3.7,25.0,1.0,0,25,375,85,271,0,1.55,-1.440904,-0.940904,-5,-10,-15
308784,308784,zkuCMAWZ2sN5nKdjRLNSbPiAfM8iseEjnce05zpeKE0=,7.0,14.0,1.60,1.3,25.0,0.0,0,445,445,85,608,0,1.20,-0.144751,0.105249,-5,-10,-15
308999,308999,zo0r1q2N+CspUDGVpNX3oEQxD9TW9oLzAI+u4CnPXgQ=,11.0,10.0,1.35,1.8,25.0,0.0,0,424,177,23,630,0,1.35,-0.224336,-0.249336,-5,-10,-15

In [119]:
test_df[test_df.reward_vaso5==-5]

,Unnamed: 0,hosp_id,interval,sofa_total,norepi_equiv,lactate,action,dead_90,reward_orig,state,next_state,new_state,new_next_state,last_record,vaso_change,reward_intm1,reward_intm2,reward_vaso5,reward_vaso10,reward_vaso15
367,367,+40TQ91K9R0c0RU/llyphvMHKIX5g0+K8mh31Bb1z7M=,9.0,6.0,2.00,2.5,20.0,0.0,0,19,19,23,519,0,1.50,-0.025000,-0.050000,-5,-10,-15
370,370,+40TQ91K9R0c0RU/llyphvMHKIX5g0+K8mh31Bb1z7M=,12.0,6.0,0.50,2.5,19.0,0.0,0,271,484,82,374,0,1.50,0.625000,1.250000,-5,-10,-15
1250,1250,+FNJDBKJj1GpwiywY3QGxdoVf3Lqvn7+nqBK57i4ZVk=,8.0,20.0,1.45,12.6,10.0,1.0,0,388,47,85,522,0,1.45,-1.083736,-0.958736,-5,-10,-15
1251,1251,+FNJDBKJj1GpwiywY3QGxdoVf3Lqvn7+nqBK57i4ZVk=,9.0,19.0,5.40,13.3,10.0,1.0,0,47,47,522,478,0,3.95,-0.025000,-0.050000,-5,-10,-15
1255,1255,+FNJDBKJj1GpwiywY3QGxdoVf3Lqvn7+nqBK57i4ZVk=,13.0,19.0,4.05,13.3,10.0,1.0,0,366,258,311,270,0,1.35,1.000000,2.000000,-5,-10,-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302906,302906,yYCHH4EJ+uEED2tgCk+eLPZNO1+D+E2UyaEJcE/xQUY=,7.0,12.0,2.00,1.7,5.0,1.0,0,369,438,23,153,0,1.50,0.734898,0.709898,-5,-10,-15
305287,305287,z/YR5NGfroKE3TKnOYqg9Qx/RzB/2oofohcicpuKgGo=,9.0,10.0,4.00,1.5,10.0,0.0,0,287,28,522,333,0,3.00,0.125000,0.250000,-5,-10,-15
305449,305449,z1RhyErEXD8w6lQe61rKfCLHZ00TI+4VG18w9n57S4c=,8.0,17.0,1.10,5.7,5.0,1.0,0,341,635,618,555,0,1.10,-1.020703,-0.270703,-5,-10,-15
305450,305450,z1RhyErEXD8w6lQe61rKfCLHZ00TI+4VG18w9n57S4c=,9.0,11.0,0.00,7.1,1.0,1.0,0,635,366,555,618,0,1.10,-1.332625,-2.082625,-5,-10,-15
305452,305452,z1RhyErEXD8w6lQe61rKfCLHZ00TI+4VG18w9n57S4c=,11.0,12.0,0.00,10.2,21.0,1.0,0,366,521,311,9,1,1.10,0.000000,0.000000,-5,-10,-15

In [5]:
# Compute mortality on training dataset for old state
state_num = 750
action_num = 25

state_action_m = np.zeros((state_num, action_num, 2), dtype=np.float32)
state_m = np.zeros((state_num, 2), dtype=np.float32)


# Sum up
#train_df["wt_mort"]=0
for hosp_id in train_df.hosp_id.unique().tolist():
  #print("Hosp_id:", hosp_id)
  subset_df = train_df[train_df.hosp_id == hosp_id]
  
  n_state = len(subset_df)
  if n_state == 0:
    continue  
  weight = 1.0 / n_state
  
  for idx in subset_df.index:
    state = int(subset_df.loc[idx, "state"] - 1)
    action = int(subset_df.loc[idx, "action"] - 1)
    outcome = float(subset_df.loc[idx, "dead_90"])    
        
    state_action_m[state][action][0] += outcome * weight
    state_action_m[state][action][1] += weight
    
    state_m[state][0] += outcome * weight
    state_m[state][1] += weight
  
# Normalize
for state in range(state_num):
  weight = state_m[state][1]
  if weight > 0.0:
    state_m[state][0] /= weight  
  
  for action in range(action_num):
    weight = state_action_m[state][action][1]
    if weight > 0.0:
      state_action_m[state][action][0] /= weight
    else:
      state_action_m[state][action][0] = state_m[state][0]

In [4]:

import numpy as gfg
  
# reshaping the array from 3D
# matrice to 2D matrice.
arr_reshaped = state_action_m.reshape(state_action_m.shape[0], -1)
  
# saving reshaped array to file.
gfg.savetxt("data_noshuffle\state_action_m.txt", arr_reshaped)
  
# retrieving data from file.
#loaded_arr = gfg.loadtxt("geekfile.txt")

In [6]:
# Compute mortality on training dataset for new state
state_num = 750
action_num = 25

state_action_m_new = np.zeros((state_num, action_num, 2), dtype=np.float32)
state_m_new = np.zeros((state_num, 2), dtype=np.float32)


# Sum up
#train_df["wt_mort_new"]=0
for hosp_id in train_df.hosp_id.unique().tolist():
  #print("Hosp_id:", hosp_id)
  subset_df = train_df[train_df.hosp_id == hosp_id]
  
  n_state = len(subset_df)
  if n_state == 0:
    continue  
  weight = 1.0 / n_state
  
  for idx in subset_df.index:
    state = int(subset_df.loc[idx, "new_state"] - 1)
    action = int(subset_df.loc[idx, "action"] - 1)
    outcome = float(subset_df.loc[idx, "dead_90"])    
        
    state_action_m_new[state][action][0] += outcome * weight
    state_action_m_new[state][action][1] += weight
    
    state_m_new[state][0] += outcome * weight
    state_m_new[state][1] += weight
  
# Normalize
for state in range(state_num):
  weight = state_m_new[state][1]
  if weight > 0.0:
    state_m_new[state][0] /= weight  
  
  for action in range(action_num):
    weight = state_action_m_new[state][action][1]
    if weight > 0.0:
      state_action_m_new[state][action][0] /= weight
    else:
      state_action_m_new[state][action][0] = state_m_new[state][0]

In [14]:
# reshaping the array from 3D
# matrice to 2D matrice.
arr_reshaped1 = state_action_m_new.reshape(state_action_m_new.shape[0], -1)
  
# saving reshaped array to file.
gfg.savetxt("data_noshuffle\state_action_m_new.txt", arr_reshaped1)
  
# retrieving data from file.
#loaded_arr = gfg.loadtxt("geekfile.txt")

In [3]:
from random import sample
def comput_mort(df,state_input,policy,state_action_m,n,nboot):
  unique_id=(test_df.hosp_id).unique().tolist()
  mort = []
  
  nboot =nboot
  for i in range(nboot):
    sample_id = sample(unique_id,n)
    test_df1=test_df[test_df.hosp_id.isin (sample_id)]
    test_df1 = test_df1.reset_index(drop=True)
    tot_m =0.0
    add_cnt = 0
    for test_id in test_df1.index:
      state = int(test_df1.loc[test_id, state_input] - 1)

      action = policy.loc[state, "action"] - 1
      
      m = state_action_m[state][action][0]
      tot_m += m
      add_cnt += 1
    mort.append(tot_m/add_cnt)
 
  return mort

In [ ]:
intm3_mort=comput_mort(test_df,"state",intm3_p,state_action_m,5000,100)
intm3_mort_new=comput_mort(test_df,"new_state",intm3_p_new,state_action_m_new,5000,100)

In [18]:
intm2_mort=comput_mort(test_df,"state",intm2_p,state_action_m,5000,100)
intm2_mort_new=comput_mort(test_df,"new_state",intm2_p_new,state_action_m_new,5000,100)
intm1_mort=comput_mort(test_df,"state",intm1_p,state_action_m,5000,100)
intm1_mort_new=comput_mort(test_df,"new_state",intm1_p_new,state_action_m_new,5000,100)
vaso3_mort=comput_mort(test_df,"state",vaso3_p,state_action_m,5000,100)
vaso3_mort_new=comput_mort(test_df,"new_state",vaso3_p_new,state_action_m_new,5000,100)
vaso2_mort=comput_mort(test_df,"state",vaso2_p,state_action_m,5000,100)
vaso2_mort_new=comput_mort(test_df,"new_state",vaso2_p_new,state_action_m_new,5000,100)
vaso1_mort=comput_mort(test_df,"state",vaso1_p,state_action_m,5000,100)
vaso1_mort_new=comput_mort(test_df,"new_state",vaso1_p_new,state_action_m_new,5000,100)

In [ ]:
is_mort = pd.DataFrame(list(zip(mort_rand, mort_clin, mort_ai,intm1_mort,\
                            intm2_mort,intm3_mort,vaso1_mort,vaso2_mort,vaso3_mort,mort_rand_new,\
                            mort_clin_new, mort_ai_new, intm1_mort_new,intm2_mort_new,intm3_mort_new,\
                            vaso1_mort_new,vaso2_mort_new ,vaso3_mort_new)),\
                   columns =['Random', 'Clinician',"AI","AI_Intm1","AI_Intm2","AI_Intm3",\
                             "AI_vaso1","AI_vaso2","AI_vaso3",'Random_new', 'Clinician_new',"AI_new","AI_Intm1_new",\
                             "AI_Intm2_new", "AI_Intm3_new", "AI_vaso1_new","AI_vaso2_new","AI_vaso3_new"])

In [26]:
is_mort.to_csv(r"data_noshuffle\is_mort.csv", index=False)
#mort_old.to_csv(r"data_noshuffle\is_mort_old.csv", index=False)